#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.156.1.10:1000/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: eshopweb
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://cvm.cheungbo.cn:3306/eshop_hcc?characterEncoding=utf8&useSSL = false
#    url: jdbc:mysql://127.0.0.1:3306/eshop_hcc?characterEncoding=utf8
    username: cvmmysql
    password: cvmmysql
#    username: root
#    password: 123456
  application:
    name: eshopweb
  aop:
    auto: true
  redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 5
      timeout: 60000
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:com/eshop/serviceweb/mapper/xml/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
logging:
  file: /log/eshop/web/eshopweb.log
  level:
    com:
      eshop:
        serviceweb:
          mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

file:
  upload:
    path: /upload/
    image-format: jpg,png,gif
    video-format: mp4,avi,mkv
