#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.156.1.10:1000/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: eshopapp
server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://cvm.cheungbo.cn:3306/eshop_test?characterEncoding=utf8&useSSL = false
    #    url: jdbc:mysql://127.0.0.1:3306/eshop_hcc?characterEncoding=utf8
    username: cvmmysql
    password: cvmmysql
  application:
    name: eshopapp
  aop:
    auto: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 5
    timeout: 60000
    password: 123456
    database: 0
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
mybatis:
  mapper-locations: classpath:com/eshop/serviceapp/mapper/xml/*Mapper.xml
  configuration:
    cache-enabled: true
logging:
  file: /log/eshop/app/eshopapp.log
  level:
    com:
      eshop:
        serviceapp: debug
#          mapper: debug


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
